services:
  - type: web
    name: facefit-backend
    env: node
    nodeVersion: 16
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 24h
      - key: JWT_ADMIN_SECRET
        generateValue: true
      - key: JWT_ADMIN_EXPIRATION
        value: 24h 